import prisma from "../../config/prisma";
import { generateSignedURL, deletePDFFromSupabase } from "../../config/supabase";
import { sendQuotationEmail } from "../../services/email.service";
import { generateQuotationPDF } from "../../services/quotation-pdf.service";

// Company prefix mapping for estimate numbers
const COMPANY_PREFIX_MAP: Record<string, string> = {
  'Solarica Energy India Pvt Ltd': 'SEI',
  'Solarica Systems Pvt Ltd': 'SS',
  'Solarica Fabtech Pvt Ltd': 'SF',
  'Solarica Industries Pvt Ltd': 'SI',
  'Solarica Greenwheels Pvt Ltd': 'SG'
};

// Get next estimate number for a company (dynamically generated by finding highest existing number)
export const getNextEstimateNumberModel = async (companyName: string): Promise<string> => {
  const prefix = COMPANY_PREFIX_MAP[companyName];

  if (!prefix) {
    throw new Error(`Unknown company: ${companyName}`);
  }

  // Find the highest existing number with this prefix from the invoices table
  // Estimates from SimpleQuotationForm/ExportQuotationForm are saved to invoices table
  const latestInvoice = await prisma.invoice.findFirst({
    where: {
      invoiceNumber: {
        startsWith: prefix
      }
    },
    orderBy: {
      invoiceNumber: 'desc'
    },
    select: {
      invoiceNumber: true
    }
  });

  // Extract number and find the max
  let maxNumber = 0;

  if (latestInvoice?.invoiceNumber) {
    const match = latestInvoice.invoiceNumber.match(new RegExp(`${prefix}-(\\d+)`));
    if (match) {
      maxNumber = parseInt(match[1], 10);
    }
  }

  // Next number is max + 1
  const nextNumber = maxNumber + 1;

  // Format with leading zeros (e.g., 01, 02, ... 99, 100)
  const formattedNumber = nextNumber.toString().padStart(2, '0');
  return `${prefix}-${formattedNumber}`;
};


// Create new quotation
export const createQuotationModel = async (
  companyName: string,
  companyEmail: string,
  companyPhone: string,
  systemCapacityKw: number,
  systemCost: number,
  createdById: string,
  items: Array<{
    name: string;
    specification?: string;
    make1?: string;
    make2?: string;
    quantity: string;
  }>,
  fromCompanyName?: string,
  consumerNumber?: string,
  BillingNumber?: string,
  CustomerNumber?: string,
  gstNumber?: string,

  // New Frontend Fields
  customerType?: string,
  subsidyType?: string,
  onGrid?: string,
  phase?: string,
  gstRate?: number,
  numberOfFlats?: number,

  // Financial Override (from Frontend)
  gstAmount?: number,
  totalAmount?: number,
  subsidyAmount?: number,
  netPayableAmount?: number,
  validityDays?: number
) => {
  // Validate basic inputs
  if (!companyName || !companyEmail) {
    throw new Error('Required fields are missing');
  }

  // Verify user exists
  const user = await prisma.user.findUnique({
    where: { id: createdById }
  });
  if (!user) {
    throw new Error(`User with ID ${createdById} does not exist`);
  }
  // Create quotation with items in a transaction
  const result = await prisma.$transaction(async (tx: any) => {
    // Create the quotation
    const quotation = await tx.quotation.create({
      data: {
        companyName,
        companyEmail,
        companyPhone,
        systemCapacityKw,
        systemCost,
        gstAmount: gstAmount || 0,
        totalAmount: totalAmount || 0,
        subsidyAmount: subsidyAmount || 0,
        netPayableAmount: netPayableAmount || 0,
        gstRate,
        customerType,
        subsidyType,
        onGrid,
        phase,
        numberOfFlats,
        fromCompanyName,
        createdById,
        consumerNumber,
        BillingNumber,
        CustomerNumber,
        gstNumber,
        validityDays,
        status: "DRAFT"
      },
      include: {
        createdBy: {
          select: {
            id: true,
            name: true,
            email: true,
            role: {
              select: {
                name: true
              }
            }
          }
        }
      }
    });
    // Create quotation items
    if (items && items.length > 0) {
      await tx.quotationItem.createMany({
        data: items.map((item: any) => ({
          quotationId: quotation.id,
          specification: item.specification || null,
          specification1: item.specification1 || item['specification-1'] || null,
          specification2: item.specification2 || item['specification-2'] || null,
          specification3: item.specification3 || item['specification-3'] || null,
          specification7: item.specification7 || item['specification-7'] || null,
          specification8: item.specification8 || item['specification-8'] || null,
          specification9: item.specification9 || item['specification-9'] || null,
          make1: item.make1,
          make2: item.make2
        }))
      });
    }
    return quotation;
  });
  return result;
};
// Send quotation email
export const sendQuotationEmailModel = async (quotationId: string) => {
  const quotation = await prisma.quotation.findUnique({
    where: { id: quotationId },
    include: {
      createdBy: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      items: true
    }
  });
  if (!quotation) {
    throw new Error('Quotation not found');
  }
  if (!quotation.pdfFilePath) {
    throw new Error('PDF not generated for this quotation');
  }
  // Generate signed URL for PDF
  const pdfURL = await generateSignedURL(quotation.pdfFilePath, 'quotations');
  // Send email
  await sendQuotationEmail(quotation, pdfURL);
  // Update quotation status
  return await prisma.quotation.update({
    where: { id: quotationId },
    data: {
      emailSent: true,
      emailSentAt: new Date(),
      status: "SENT"
    },
  });
};
// Get all quotations
export const getAllQuotationsModel = async (userId: string, userRole: any, filters: any = {}) => {
  const { company } = filters;
  const where: any = {};

  // Enforce role-based visibility
  const normalizedRole = (typeof userRole === 'object' ? userRole?.name : userRole)?.toLowerCase()?.trim();
  if (normalizedRole !== 'admin' && normalizedRole !== 'operation' && normalizedRole !== 'operations' && normalizedRole !== 'accounting' && normalizedRole !== 'account') {
    where.createdById = userId;
  }

  if (company) {
    where.fromCompanyName = {
      contains: company,
      mode: 'insensitive'
    };
  }

  return await prisma.quotation.findMany({
    where,
    include: {
      createdBy: {
        select: {
          id: true,
          name: true,
          email: true,
          role: { select: { name: true } }
        }
      },
      items: true
    },
    orderBy: { createdAt: 'desc' }
  });
};

// Update quotation status
export const updateQuotationStatusModel = async (id: string, status: string) => {
  return await prisma.quotation.update({
    where: { id },
    data: { status }
  });
};

// Get quotation by ID
export const getQuotationByIdModel = async (id: string) => {
  return await prisma.quotation.findUnique({
    where: { id },
    include: {
      createdBy: {
        select: {
          id: true,
          name: true,
          email: true,
          role: { select: { name: true } }
        }
      },
      items: true
    }
  });
};


// Generic update quotation
export const updateQuotationModel = async (id: string, data: any) => {
  return await prisma.quotation.update({
    where: { id },
    data
  });
};

// Update quotation status with reason (for rejection)
export const rejectQuotationWithReasonModel = async (id: string, reason: string) => {
  return await prisma.quotation.update({
    where: { id },
    data: {
      status: 'REJECTED',
      rejectionReason: reason
    },
    include: {
      createdBy: {
        select: {
          id: true,
          name: true,
          email: true
        }
      }
    }
  });
};

// Delete quotation
export const deleteQuotationModel = async (id: string) => {
  const quotation = await prisma.quotation.findUnique({ where: { id } });

  if (!quotation) {
    throw new Error('Quotation not found');
  }

  // Delete PDF from Supabase Storage if exists
  if (quotation.pdfFilePath) {
    await deletePDFFromSupabase(quotation.pdfFilePath, 'quotations');
  }

  // Delete extra docs if they exist
  // @ts-ignore
  if (quotation.doc1) await deletePDFFromSupabase(quotation.doc1, 'documents');
  // @ts-ignore
  if (quotation.doc2) await deletePDFFromSupabase(quotation.doc2, 'documents');
  // @ts-ignore
  if (quotation.doc3) await deletePDFFromSupabase(quotation.doc3, 'documents');


  await prisma.quotation.delete({ where: { id } });
  return { message: 'Quotation deleted successfully' };
};

// Get PDF download URL
export const getPDFDownloadURLModel = async (id: string) => {
  const quotation = await prisma.quotation.findUnique({ where: { id } });

  if (!quotation) {
    throw new Error('Quotation not found');
  }

  if (!quotation.pdfFilePath) {
    throw new Error('No PDF available for this quotation');
  }

  const signedURL = await generateSignedURL(quotation.pdfFilePath, 'quotations');
  return { url: signedURL };
};

export const generateQuotationPDFModel = async (quotationId: string, extraData: any = {}) => {
  const quotation = await prisma.quotation.findUnique({
    where: { id: quotationId },
    include: {
      createdBy: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      items: true
    }
  });
  if (!quotation) {
    throw new Error('Quotation not found');
  }

  // Merge database fields with extra data from the request
  const combinedData = {
    ...quotation,
    ...extraData,
    // Merge items: use extraData items if available (has fresh form data), otherwise use DB items
    items: extraData.items && extraData.items.length > 0 ? extraData.items : quotation.items
  };

  // Generate PDF using template
  const pdfFilePath = await generateQuotationPDF(combinedData);

  // Update quotation with PDF path
  const updatedQuotation = await prisma.quotation.update({
    where: { id: quotationId },
    data: { pdfFilePath },
    include: {
      createdBy: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      items: true
    }
  });
  return updatedQuotation;
};

// Update quotation documents (images)
export const updateQuotationDocsModel = async (id: string, docs: { doc1?: string, doc2?: string, doc3?: string }) => {
  return await prisma.quotation.update({
    where: { id },
    // @ts-ignore
    data: docs
  });
};

export const getQuotationDocsURLModel = async (id: string) => {
  const quotation = await prisma.quotation.findUnique({ where: { id } });

  if (!quotation) {
    throw new Error('Quotation not found');
  }

  const urls: { doc1?: string, doc2?: string, doc3?: string } = {};

  // @ts-ignore
  if (quotation.doc1) urls.doc1 = await generateSignedURL(quotation.doc1, 'documents');
  // @ts-ignore
  if (quotation.doc2) urls.doc2 = await generateSignedURL(quotation.doc2, 'documents');
  // @ts-ignore
  if (quotation.doc3) urls.doc3 = await generateSignedURL(quotation.doc3, 'documents');

  return urls;
};

